DROP SEQUENCE IF EXISTS member_seq CASCADE;
DROP TABLE IF EXISTS member CASCADE;

DROP SEQUENCE IF EXISTS role_seq CASCADE;
DROP TABLE IF EXISTS role CASCADE;

DROP TABLE IF EXISTS member_role CASCADE;